name: Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add execute permission to gradlew
        run: chmod +x gradlew

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/*.jar

      - name: Publish
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'SuperCrafting'
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_SECRET }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          BUILD_VERSION: ${{ github.run_number }}
        run: ./gradlew publish