name: Release

on:
  workflow_dispatch:
    inputs:
      version:
          description: 'Version for the release'
          required: true
          default: '1.0.0'
      tag:
        description: 'Tag for the release'
        required: true
        default: 'v1.0.0'
      description:
        description: 'Description for the release'
        required: false
        default: 'Release description'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add execute permission to gradlew
        run: chmod +x gradlew

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Release
        id: create_release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ github.event.inputs.description }}
          draft: false
          prerelease: false